### ISSUE TITLE
Input is not robust enough

### ISSUE THREAD

**Issue by zlovec2012** [ODonnell-Lipidomics/LipidFinder#2]
Integer overflow will happen in python2. Changing "astype("int")" to "astype("int64")" in SampleMeansCalc.py will be work.

On LipidFinder websit, selecting an integer in retention time threshold will result in wrong output.

**Comment by JAlvarezJarreta** [comment]
Thank you @zlovec2012. I'll have a look into it and push the change to LIPIDMAPS.

On a side note, soon we will stop providing support to Python 2 as it has finally reached it's EoL :cry:

**Comment by s-andrews** [comment]
LipidFinder on the LipidMAPS site is running on Python3 if that makes any difference in debugging this.
